"""Compose the speckit-compliant `spec.md` for a tutorial chapter.

Per `contracts/spec-output-format.md`. Refuses to emit a spec whose
Functional Requirements include any code-bearing requirement without a
`(book pp ... §A.B[, Program N.N])` citation.
"""

from __future__ import annotations

import os
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from tutorial_specify.charter import ChapterPlan, ChapterSources, ChapterTutorial, TutorialInputs
from tutorial_specify.modes import MODE_REGISTRY
from tutorial_specify.pdf_extract import CodeBlock


CONSTITUTION_VERSION = "1.2.0"


def _utc_date_for_inputs(inputs_hashes: dict[str, str]) -> str:
    """Deterministic date string derived from the input hashes.

    Per /research.md Decision 9, we don't embed wall-clock time; we use UTC
    today date based on the latest run, which still gives byte-identity for
    the SAME run (the date is computed once per invocation, then reused).
    """
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _detect_chapter_pretty_name(tutorial: ChapterTutorial) -> str:
    title = tutorial.title.strip()
    return title or "Tutorial Chapter"


def render_spec(
    *,
    feature_dir_name: str,  # e.g. "002-tutorial-ch04"
    chapter_id: str,
    plan: ChapterPlan,
    sources: ChapterSources,
    tutorial: ChapterTutorial,
    inputs: TutorialInputs,
    blocks_for_target: dict[str, list[CodeBlock]],
    inputs_hashes: dict[str, str],
    sync_impact_report: str | None = None,
) -> str:
    """Build the full `spec.md` markdown body.

    `blocks_for_target` maps tutorial file paths or use-case names to the
    pre-parse-checked code blocks the extractor associated with them.
    """
    composer = MODE_REGISTRY[plan.mode]
    sections = composer(plan, blocks_for_target)

    pretty = _detect_chapter_pretty_name(tutorial)
    date = _utc_date_for_inputs(inputs_hashes)

    pieces: list[str] = []

    if sync_impact_report:
        pieces.append("<!--\n" + sync_impact_report.strip() + "\n-->")
        pieces.append("")

    pieces.append(f"# Feature Specification: {pretty}")
    pieces.append("")
    pieces.append(f"**Feature Branch**: `{feature_dir_name}`")
    pieces.append(f"**Created**: {date}")
    pieces.append("**Status**: Draft")
    pieces.append(
        f"**Input**: Generated by `/tutorial-specify {chapter_id}` from "
        f"`{_rel(inputs.plan)}`."
    )
    pieces.append(
        f"**Constitution**: `.specify/memory/constitution.md` v{CONSTITUTION_VERSION} — "
        f"Principle VI (Tutorial Charter Compliance) governs this spec; downstream "
        f"design and implementation MUST be based on `GLP_ART.pdf` in source per "
        f"Principle I and the chapter's mode-specific Functional Requirements."
    )
    pieces.append(f"**Tutorial Mode**: {plan.mode}")
    pieces.append("")

    # Empty Clarifications stub for downstream /speckit-clarify
    pieces.append("## Clarifications")
    pieces.append("")
    pieces.append("(No clarifications yet; run `/speckit-clarify` to populate.)")
    pieces.append("")

    pieces.append("## User Scenarios & Testing *(mandatory)*")
    pieces.append("")
    pieces.append(sections.get("user_scenarios", "").strip() or "(none)")
    pieces.append("")

    pieces.append("## Requirements *(mandatory)*")
    pieces.append("")
    pieces.append(sections.get("requirements", "").strip() or "(none)")
    pieces.append("")

    if sections.get("key_entities"):
        pieces.append(sections["key_entities"].strip())
        pieces.append("")

    pieces.append("## Success Criteria *(mandatory)*")
    pieces.append("")
    pieces.append(sections.get("success_criteria", "").strip() or "(none)")
    pieces.append("")

    pieces.append("## Assumptions")
    pieces.append("")
    pieces.append(_assumptions(inputs, plan, sources))
    pieces.append("")

    body = "\n".join(pieces).rstrip() + "\n"

    _validate_no_pdf_pages(body)
    _validate_citations_present(body, plan)
    return body


def _assumptions(inputs: TutorialInputs, plan: ChapterPlan, sources: ChapterSources) -> str:
    src_count = len(sources.sources)
    return (
        f"- This spec was generated from `{_rel(inputs.plan)}` (Mode: "
        f"`{plan.mode}`), `{_rel(inputs.sources)}` ({src_count} sources), "
        f"`{_rel(inputs.tutorial)}`, and `olamni/tutorial/charter.md` per "
        f"Constitution Principle VI.\n"
        f"- Code-bearing requirements MUST be implemented from `GLP_ART.pdf` "
        f"in source, never from model memory or training (FR-009 in the "
        f"tool's own spec; mirrored here per FR design).\n"
        f"- The GLP REPL is the unified GLP tool; tutorial code MUST load "
        f"and run via `cd glp_runtime/bin; dart run glp_repl.dart`.\n"
        f"- File names and structure MUST match the chapter plan exactly; "
        f"divergence is amended in the plan first, then the work proceeds."
    )


def _rel(path: Path) -> str:
    return path.as_posix()


def _validate_no_pdf_pages(body: str) -> None:
    """`PDF p N` / `PDF pp N–M` MUST NOT appear in the output (FR-003)."""
    if re.search(r"\bPDF\s+pp?\s+\d", body):
        raise ValueError(
            "render_spec produced a citation containing PDF page numbers; "
            "FR-003 forbids this — citations MUST use book pages only"
        )


_BOOK_CITATION_RE = re.compile(r"\(book\s+pp?\s+[0-9]")


def _validate_citations_present(body: str, plan: ChapterPlan) -> None:
    """Every code-bearing FR row MUST carry a citation; refuse to write otherwise.

    Soft validation: we look at FR lines mentioning a `.glp` file and require
    them to contain either a book-page citation or a `see chapter plan source
    references` placeholder (when the extractor returned no blocks for a row,
    which itself indicates an upstream extraction issue the operator should
    investigate; we accept the placeholder rather than refuse to write).
    """
    in_fr = False
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("### Functional Requirements"):
            in_fr = True
            continue
        if in_fr and stripped.startswith("## "):
            in_fr = False
        if in_fr and stripped.startswith("- **FR-") and ".glp" in stripped:
            if not (
                _BOOK_CITATION_RE.search(stripped)
                or "see chapter plan source references" in stripped
                or "Constitution" in stripped
            ):
                raise ValueError(
                    "FR row references a .glp file without a book-page "
                    f"citation; FR-003 violation: {stripped[:120]}..."
                )


def write_atomic(path: Path, body: str) -> None:
    """Write `body` to `path` atomically (temp + rename)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".spec.", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(body)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


def render_sync_impact_report(
    *,
    chapter_id: str,
    old_hashes: dict[str, str],
    new_hashes: dict[str, str],
) -> str:
    """Build the HTML-comment Sync Impact Report body for FR-023."""
    lines = [
        f"SYNC IMPACT REPORT — regenerated /tutorial-specify {chapter_id}",
        "Inputs whose content changed since previous run:",
    ]
    for path in sorted(set(old_hashes) | set(new_hashes)):
        old = old_hashes.get(path)
        new = new_hashes.get(path)
        if old != new:
            old_short = (old or "<absent>")[:12]
            new_short = (new or "<absent>")[:12]
            lines.append(f"- {path}: {old_short} -> {new_short}")
    return "\n".join(lines)
